/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Variant } from "./components/pc-button/pc-button";
export { Variant } from "./components/pc-button/pc-button";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PcButton {
        "ariaLabel": string;
        "disabled": boolean;
        "icon": string;
        "type": 'button' | 'submit' | 'reset';
        "variant": Variant;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPcButtonElement extends Components.PcButton, HTMLStencilElement {
    }
    var HTMLPcButtonElement: {
        prototype: HTMLPcButtonElement;
        new (): HTMLPcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pc-button": HTMLPcButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PcButton {
        "ariaLabel"?: string;
        "disabled"?: boolean;
        "icon"?: string;
        "type"?: 'button' | 'submit' | 'reset';
        "variant"?: Variant;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pc-button": PcButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pc-button": LocalJSX.PcButton & JSXBase.HTMLAttributes<HTMLPcButtonElement>;
        }
    }
}
